name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [latest, bionic, focal]

    env:
      FLAVOR: ${{ matrix.flavor }}

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Docker registry login
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@v1.2.10
        with:
          command: docker-builder
          build-args: FLAVOR
          tag-suffix: ${{ env.FLAVOR }}
          dry-run: ${{ github.ref != 'refs/heads/main' }}
          last-only: true
          major-minor: false
